### ISSUE TITLE
Design a scenario

### ISSUE THREAD

**Issue by dpakalarry** [jarbus/multiagent-particle-envs#1]

**Comment by dpakalarry** [comment]
Will design a scenario in terms of the game theory concepts that we want to implement

**Comment by jarbus** [comment]
With regards to game theory, I’d recommend making sure you at least explicitly state the following:

The possible actions an agent can take
The rewards per outcome
The properties of any other entities in the simulation
The theoretical Nash equilibrium if it exists

**Comment by jarbus** [comment]
Designing multiple different simulations may also be a stretch goal - the more ideas the better! We don’t need to implement all of them but rapid prototyping may help with a final design.

**Comment by dpakalarry** [comment]
Idea 1 added to Scenarioideas.md

**Comment by jarbus** [comment]
Let’s shoot for 3 scenarios by Wednesday, July 24th

**Comment by dpakalarry** [comment]
Pivot to the race scenario which uses the existing engine

**Comment by SimplySonder** [comment]
Added Idea 3, which is a basic design for Hunger Games
