### ISSUE TITLE
Qlearning with gym environment

### ISSUE THREAD

**Issue by ymkymkymkymx** [jarbus/multiagent-particle-envs#3]

**Comment by jarbus** [comment]
Make sure to develop your code in a separate folder in this repository. Also make sure to post progress in the comments of this thread!

**Comment by ymkymkymkymx** [comment]
I just implemented the Q learning for mountain car agent and I created a new folder named agents_using_gym to keep the codes.
Also, I am just using gym==0.13.1 instead of 0.10.5.

**Comment by jarbus** [comment]
Try to implement this agent in a Multi-Agent scenario by Wednesday July 24th

**Comment by jarbus** [comment]
Work on understanding DDPG and implementing Q-learning into multi-agent env
