### ISSUE TITLE
Begin writing documentation for this repo, explaining how the system works

### ISSUE THREAD

**Issue by jarbus** [jarbus/multiagent-particle-envs#5]
Write up documentation plus make some sort of graph (can be ascii art) to show how each class interacts in the entire simulation. Explain how the scenarios, agents, and environments all come into play, and when.

**Comment by jarbus** [comment]
Documentation by Saturday July 20th

**Comment by ymkymkymkymx** [comment]
Need help: I want to know how the agents interact with the environments, specifically, what functions do they call to get the information of their states, their action space, or to make a move. Also, how do to add agents into the environment.

**Comment by jarbus** [comment]
Updated documentation.md with basic info pertaining to how overall system works

**Comment by jarbus** [comment]
Will be writing documentation for race scenario, and documentation + implementing maddpg from openai

**Comment by jarbus** [comment]
Added a bit of race documentation and also started documenting how their MADDPG agent works in https://github.com/jarbus/maddpg
