### ISSUE TITLE
Implement Race Scenario using Core/Environment Redesign + Simple Agents

### ISSUE THREAD

**Issue by jarbus** [jarbus/multiagent-particle-envs#8]
Work on implementing the race scenario, tweaking core or environment if you need to. Test implementation using simple agents (always tries to move far, copies last outcome, etc). Make sure in your design you explicitly say what action(), reward(), and observation() take in as input and return as output so that the agent teams can implement their designs.

**Comment by zrysnd** [comment]
Modified environment class added as envRace.py. Modified core.py added as coreRace.py. Script to run race scenario added as raceScript.py ( need it because main script specifies which environment to use, will integrate to our final main script ). Still working on race scenario file.
