### ISSUE TITLE
Predator/Prey Scenario

### ISSUE THREAD

**Issue by jarbus** [jarbus/multiagent-particle-envs#9]
Begin working on predator/prey scenario. You guys came up with lots of great ideas different ways we could tweak it, would love to be able to prototype some of them! For this week, work on modifying their code to add different twists to their design, so we can compare and contrast how the differences in scenarios affect agent performance. You can easily do this by making a bunch of script files, or by making an easy way to choose the modification in a single file.

**Comment by dpakalarry** [comment]
Ideas added to the markdown document

**Comment by dpakalarry** [comment]
Parameterized tag and simple watering hole completed
